#配置GitHub登录的app信息
github:
  client:
    id: Iv1.608c3ae1ace91189
    secret: b209f8d0f8ec98da73bf58adf497a89ea6c99e0a
  redirect:
    uri: http://localhost:8080/callBack
#阿里云OSS对象存储配置
aliyun:
  endpoint: https://oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI4G9CG1Eap8nR6pjvJg9S
  accessKeySecret: Sq6BJ8qhvmyQBsf7dvG9RM0ZzMdqbn
  bucketName: marker-fileupload
  filePatten: images/
  expiration: 31104000000
#热门话题配置
hotTag:
  #显示个数
  capacity: 10
  #问题评论权重比例 问题 ：评论 = 1 ：5
  proportion: 5
#热门问题配置
hotQuestion:
  #一个月的毫秒数
  month: 2592000000
  #一周的毫秒数
  week: 604800000
  #当天的毫秒数
  day: 86400000
#配置数据库连接
spring:
  datasource:
    url: jdbc:h2:~/community
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
#关闭thymeleaf页面缓存
  thymeleaf:
    cache: false
#mybatis配置
mybatis:
  configuration:
    #开启驼峰标识
    map-underscore-to-camel-case: true
  #配置mapper.xml配置文件的位置
  mapper-locations: classpath:mapper/*.xml
  #配置别名包
  type-aliases-package: com.markloy.code_community.pojo
#配置日志信息
logging:
  level.root: info
  file:
    name: logs/community.log
    #单个日志文件保存100MB数据，超出则新建一个日志文件
    max-size: 100MB
    #日志文件保存15天
    max-history: 15

