package com.markloy.code_community.pojo;

public class CountRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_record.id
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_record.user_id
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_record.question_id
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    private Long questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_record.view_check
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    private Integer viewCheck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_record.like_check
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    private Integer likeCheck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_record.gmt_create
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    private Long gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_record.id
     *
     * @return the value of count_record.id
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_record.id
     *
     * @param id the value for count_record.id
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_record.user_id
     *
     * @return the value of count_record.user_id
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_record.user_id
     *
     * @param userId the value for count_record.user_id
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_record.question_id
     *
     * @return the value of count_record.question_id
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_record.question_id
     *
     * @param questionId the value for count_record.question_id
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_record.view_check
     *
     * @return the value of count_record.view_check
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    public Integer getViewCheck() {
        return viewCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_record.view_check
     *
     * @param viewCheck the value for count_record.view_check
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    public void setViewCheck(Integer viewCheck) {
        this.viewCheck = viewCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_record.like_check
     *
     * @return the value of count_record.like_check
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    public Integer getLikeCheck() {
        return likeCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_record.like_check
     *
     * @param likeCheck the value for count_record.like_check
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    public void setLikeCheck(Integer likeCheck) {
        this.likeCheck = likeCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_record.gmt_create
     *
     * @return the value of count_record.gmt_create
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_record.gmt_create
     *
     * @param gmtCreate the value for count_record.gmt_create
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}