package com.markloy.code_community.pojo;

public class Tag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAG.ID
     *
     * @mbg.generated Tue Sep 08 20:06:28 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAG.TAG_NAME
     *
     * @mbg.generated Tue Sep 08 20:06:28 CST 2020
     */
    private String tagName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAG.TYPE
     *
     * @mbg.generated Tue Sep 08 20:06:28 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAG.GMT_CREATE
     *
     * @mbg.generated Tue Sep 08 20:06:28 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAG.GMT_MODIFIED
     *
     * @mbg.generated Tue Sep 08 20:06:28 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAG.PARENT_ID
     *
     * @mbg.generated Tue Sep 08 20:06:28 CST 2020
     */
    private Long parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAG.ID
     *
     * @return the value of TAG.ID
     *
     * @mbg.generated Tue Sep 08 20:06:28 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAG.ID
     *
     * @param id the value for TAG.ID
     *
     * @mbg.generated Tue Sep 08 20:06:28 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAG.TAG_NAME
     *
     * @return the value of TAG.TAG_NAME
     *
     * @mbg.generated Tue Sep 08 20:06:28 CST 2020
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAG.TAG_NAME
     *
     * @param tagName the value for TAG.TAG_NAME
     *
     * @mbg.generated Tue Sep 08 20:06:28 CST 2020
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAG.TYPE
     *
     * @return the value of TAG.TYPE
     *
     * @mbg.generated Tue Sep 08 20:06:28 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAG.TYPE
     *
     * @param type the value for TAG.TYPE
     *
     * @mbg.generated Tue Sep 08 20:06:28 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAG.GMT_CREATE
     *
     * @return the value of TAG.GMT_CREATE
     *
     * @mbg.generated Tue Sep 08 20:06:28 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAG.GMT_CREATE
     *
     * @param gmtCreate the value for TAG.GMT_CREATE
     *
     * @mbg.generated Tue Sep 08 20:06:28 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAG.GMT_MODIFIED
     *
     * @return the value of TAG.GMT_MODIFIED
     *
     * @mbg.generated Tue Sep 08 20:06:28 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAG.GMT_MODIFIED
     *
     * @param gmtModified the value for TAG.GMT_MODIFIED
     *
     * @mbg.generated Tue Sep 08 20:06:28 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAG.PARENT_ID
     *
     * @return the value of TAG.PARENT_ID
     *
     * @mbg.generated Tue Sep 08 20:06:28 CST 2020
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAG.PARENT_ID
     *
     * @param parentId the value for TAG.PARENT_ID
     *
     * @mbg.generated Tue Sep 08 20:06:28 CST 2020
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }
}