package com.markloy.code_community.pojo;

public class Tag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.id
     *
     * @mbg.generated Mon Sep 14 19:32:02 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.tag_name
     *
     * @mbg.generated Mon Sep 14 19:32:02 CST 2020
     */
    private String tagName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.type
     *
     * @mbg.generated Mon Sep 14 19:32:02 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.gmt_create
     *
     * @mbg.generated Mon Sep 14 19:32:02 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.gmt_modified
     *
     * @mbg.generated Mon Sep 14 19:32:02 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.parent_id
     *
     * @mbg.generated Mon Sep 14 19:32:02 CST 2020
     */
    private Long parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.id
     *
     * @return the value of tag.id
     *
     * @mbg.generated Mon Sep 14 19:32:02 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.id
     *
     * @param id the value for tag.id
     *
     * @mbg.generated Mon Sep 14 19:32:02 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.tag_name
     *
     * @return the value of tag.tag_name
     *
     * @mbg.generated Mon Sep 14 19:32:02 CST 2020
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.tag_name
     *
     * @param tagName the value for tag.tag_name
     *
     * @mbg.generated Mon Sep 14 19:32:02 CST 2020
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.type
     *
     * @return the value of tag.type
     *
     * @mbg.generated Mon Sep 14 19:32:02 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.type
     *
     * @param type the value for tag.type
     *
     * @mbg.generated Mon Sep 14 19:32:02 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.gmt_create
     *
     * @return the value of tag.gmt_create
     *
     * @mbg.generated Mon Sep 14 19:32:02 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.gmt_create
     *
     * @param gmtCreate the value for tag.gmt_create
     *
     * @mbg.generated Mon Sep 14 19:32:02 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.gmt_modified
     *
     * @return the value of tag.gmt_modified
     *
     * @mbg.generated Mon Sep 14 19:32:02 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.gmt_modified
     *
     * @param gmtModified the value for tag.gmt_modified
     *
     * @mbg.generated Mon Sep 14 19:32:02 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.parent_id
     *
     * @return the value of tag.parent_id
     *
     * @mbg.generated Mon Sep 14 19:32:02 CST 2020
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.parent_id
     *
     * @param parentId the value for tag.parent_id
     *
     * @mbg.generated Mon Sep 14 19:32:02 CST 2020
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }
}