package com.markloy.code_community.pojo;

public class UserTag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tag.id
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tag.tag_name
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    private String tagName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tag.type
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tag.user_id
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tag.gmt_create
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tag.gmt_modified
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    private Long gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tag.id
     *
     * @return the value of user_tag.id
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tag.id
     *
     * @param id the value for user_tag.id
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tag.tag_name
     *
     * @return the value of user_tag.tag_name
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tag.tag_name
     *
     * @param tagName the value for user_tag.tag_name
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tag.type
     *
     * @return the value of user_tag.type
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tag.type
     *
     * @param type the value for user_tag.type
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tag.user_id
     *
     * @return the value of user_tag.user_id
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tag.user_id
     *
     * @param userId the value for user_tag.user_id
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tag.gmt_create
     *
     * @return the value of user_tag.gmt_create
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tag.gmt_create
     *
     * @param gmtCreate the value for user_tag.gmt_create
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tag.gmt_modified
     *
     * @return the value of user_tag.gmt_modified
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tag.gmt_modified
     *
     * @param gmtModified the value for user_tag.gmt_modified
     *
     * @mbg.generated Tue Sep 15 21:13:48 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }
}